### ISSUE TITLE
What do we use train Data?

### ISSUE THREAD

**Issue by jungchanghae** [jungchanghae/AGI_finalproject#4]
ImageNet-Hard dataset has only Validation dataset.
So, do we use just random split in seed 113?

**Comment by jungchanghae** [comment]
seed 113
We need to decide which class we will use. (percentage or class split)

**Comment by SangbeomLim** [comment]
> seed 113 We need to decide which class we will use. (percentage or class split)

Original Paper evaluated their model by using all of ImageNet-Hard Dataset.
I guess our methods also do not require a training process.
How about using all of the data and in case we need a training procedure, split Train/Test by 9:1?

**Comment by jungchanghae** [comment]
> I guess our methods also do not require a training process. 
I agree this.

> How about using all of the data and in case we need a training procedure, split Train/Test by 9:1?
We will proceed with this.

@PowerStream3604 @SangbeomLim
