### ISSUE TITLE
Base RPO Result

### ISSUE THREAD

**Issue by jungchanghae** [jungchanghae/AGI_finalproject#8]
```
* total: 11,465
* correct: 911
* accuracy: 7.9%
* error: 92.1%
* macro_f1: 5.9%
```

**Comment by SangbeomLim** [comment]
Was the question a 4-choice question??

**Comment by jungchanghae** [comment]
> Was the question a 4-choice question??

No. Result is just Base code. (prompt is 'a photo is _.'.)
Today, I'm going to try other things.
